services:
  # Development environment
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5174:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host

  # Production environment
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - MESHBOT_API_URL=http://meshtastic-bot-manager:8000
      - MESHBOT_API_BASE_PATH=/api/ui
      - MESHBOT_API_TIMEOUT=10000
      - MESHBOT_API_TOKEN=d9891a1ed5541ae02392b9829cb68267bf68e06c
      - MAP_DEFAULT_CENTER_LAT=0
      - MAP_DEFAULT_CENTER_LNG=0
      - MAP_DEFAULT_ZOOM=2
      - NODE_ENV=production
    ports:
      - '5175:80'
