name: Manual release

on:
  workflow_dispatch:
    inputs:
      VERSION_TAG:
        required: true
        type: string
      IS_LATEST:
        required: true
        type: boolean
        default: false
      IS_PRERELEASE:
        required: true
        type: boolean
        default: false

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ inputs.VERSION_TAG }}
            ${{ inputs.IS_LATEST && (inputs.IS_PRERELEASE && format('ghcr.io/{0}:latest-rc', github.repository) || format('ghcr.io/{0}:latest', github.repository)) || '' }}
          build-args: |
            VERSION=${{ inputs.VERSION_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
