name: Manual release

on:
  workflow_dispatch:
    inputs:
      VERSION_TAG:
        required: true
        type: string
      IS_LATEST:
        required: true
        type: boolean
        default: false
      IS_PRERELEASE:
        required: true
        type: boolean
        default: false

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    uses: ./.github/workflows/docker-build.yaml
    with:
      VERSION_TAG: ${{ inputs.VERSION_TAG }}
      IS_PRERELEASE: ${{ inputs.IS_PRERELEASE }}
      IS_LATEST: ${{ inputs.IS_LATEST }} 