name: Manual release

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  extract-dev-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get short SHA
        id: get_sha
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "VERSION_LABEL=$SHORT_SHA" >> "$GITHUB_OUTPUT"

    outputs:
      VERSION_LABEL: ${{ steps.get_sha.outputs.VERSION_LABEL }}

  build:
    needs:
      - extract-dev-tag
    uses: ./.github/workflows/docker-build.yaml
    with:
      VERSION_LABEL: ${{ needs.extract-dev-tag.outputs.VERSION_LABEL }}
      ENVIRONMENT: dev
