name: Pull Request

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Run TypeScript Check
        run: npx tsc --noEmit

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test

  build:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ghcr.io/${{ github.repository }}:pr-${{ github.event.pull_request.number }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Docker Container
        run: |
          docker run -d \
            --name meshtastic-bot-ui \
            -p 3000:80 \
            ghcr.io/${{ github.repository }}:pr-${{ github.event.pull_request.number }}

      - name: Wait for Container to Start
        run: sleep 10

      - name: Health Check
        run: |
          HEALTH_CHECK_URL="http://localhost:3000"
          MAX_RETRIES=5
          RETRY_COUNT=0

          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            if curl -s -f -o /dev/null "$HEALTH_CHECK_URL"; then
              echo "Health check passed!"
              exit 0
            fi

            echo "Health check failed, retrying in 5 seconds..."
            sleep 5
            RETRY_COUNT=$((RETRY_COUNT + 1))
          done

          echo "Health check failed after $MAX_RETRIES attempts"
          docker logs meshtastic-bot-ui
          exit 1

      - name: Cleanup
        if: always()
        run: docker rm -f meshtastic-bot-ui
