name: Release

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  extract-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Release Tag
        id: get_tag
        run: |
          echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
          echo "IS_PRERELEASE=${{ github.event.release.prerelease }}" >> "$GITHUB_OUTPUT"

    outputs:
      VERSION_TAG: ${{ steps.get_tag.outputs.VERSION_TAG }}
      IS_PRERELEASE: ${{ steps.get_tag.outputs.IS_PRERELEASE }}

  build:
    needs:
      - extract-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ needs.extract-tag.outputs.VERSION_TAG }}
            ${{ fromJson(needs.extract-tag.outputs.IS_PRERELEASE) == false && format('ghcr.io/{0}:latest', github.repository) || format('ghcr.io/{0}:latest-rc', github.repository) }}
          build-args: |
            VERSION=${{ needs.extract-tag.outputs.VERSION_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
